### ISSUE TITLE
.avsc is not appearing as avro file

### ISSUE THREAD

**Issue by ricardogaspar2** [Jason3S/vscode-avro-ext#2]
is not possible to use `.avsc` extension file right out of the box (when saving). 
When opening an `avsc` file it recognises as a JSON with comments.

![avro-vscode-issue](https://user-images.githubusercontent.com/3660448/40973343-d4ccf9c4-68bb-11e8-90a8-2e4982acae98.png)

**Comment by Jason3S** [comment]
Thank you for the feedback. What are you expecting or hoping for? `.avsc` files are JSON files.
How would you like to see it enhanced?

The only enhancement I could think of is to add JSON-Schema support to the `.avsc` files so it does some sort of grammar / structure checking.
